### ISSUE TITLE
sampling frame must be labor / work / humans

### ISSUE THREAD

**Issue by maxheld83** [soztag/denkzeug#38]
find out theories around this

**Comment by VerenaHeld** [comment]
erneut besprochen am 02.09.:
Beim Explorathon Lab sollte ein Raster gefunden werden

**Comment by maxheld83** [comment]
es sollte insbesondere geklärt werden ob:

- [ ] die items auf den Kontext "Betrieb" verengt werden sollten (oder sollte das in der condition of instruction bzw. dem leute-sampling drin stecken?)
